"""alter_table_registros_ponto_remove_column_data_hora

Revision ID: 2ba34f340b47
Revises: 627d092c8837
Create Date: 2025-08-31 14:16:28.087825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ba34f340b47'
down_revision: Union[str, Sequence[str], None] = '627d092c8837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_pontos', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
