"""alter_table_empresas_add_column_complemento

Revision ID: 2d2e6e6619ab
Revises: 2ba34f340b47
Create Date: 2025-08-31 15:43:54.845689

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d2e6e6619ab'
down_revision: Union[str, Sequence[str], None] = '2ba34f340b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.execute(
            "ALTER TABLE empresas ALTER COLUMN ativo TYPE status_registro USING ativo::status_registro;")
        batch_op.add_column(
            sa.Column('complemento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.execute(
            "ALTER TABLE empresas ALTER COLUMN ativo TYPE SMALLINT USING ativo::SMALLINT;")
        batch_op.drop_column('complemento')

    # ### end Alembic commands ###
