"""create_tables_empresas_usuarios

Revision ID: 3ee38fa9bedb
Revises: 
Create Date: 2025-08-23 21:40:04.725679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee38fa9bedb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Text(), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_empresas_id_empresa'), 'empresas', ['id_empresa'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_table('empresas_usuarios',
    sa.Column('id_empresa_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], name='empresas_usuarios_id_empresa_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='empresas_usuarios_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_empresa_usuario')
    )
    op.create_index(op.f('ix_empresas_usuarios_id_empresa_usuario'), 'empresas_usuarios', ['id_empresa_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_usuarios_id_empresa_usuario'), table_name='empresas_usuarios')
    op.drop_table('empresas_usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_empresas_id_empresa'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
