"""create_all_tables

Revision ID: 42f6fe51f374
Revises: 
Create Date: 2025-08-23 23:18:06.617400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f6fe51f374'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Text(), nullable=False),
    sa.Column('razao_social', sa.String(length=100), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa', name='empresas_pkey'),
    sa.UniqueConstraint('cnpj'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_id_empresa'), ['id_empresa'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', name='usuarios_pkey'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('empresas_usuarios',
    sa.Column('id_empresa_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.SMALLINT(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id_empresa'], name='empresas_usuarios_id_empresa_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='empresas_usuarios_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_empresa_usuario', name='empresas_usuarios_pkey'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('empresas_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_usuarios_id_empresa_usuario'), ['id_empresa_usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_usuarios_id_empresa_usuario'))

    op.drop_table('empresas_usuarios')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id_usuario'))

    op.drop_table('usuarios')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_id_empresa'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
