"""alter_table_usuarios_add_column_pis

Revision ID: 79fa9217f75f
Revises: 65e0a754d1d0
Create Date: 2025-08-31 13:53:25.009739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79fa9217f75f'
down_revision: Union[str, Sequence[str], None] = '65e0a754d1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pis', sa.String(length=11), nullable=False))
        batch_op.create_unique_constraint(None, ['pis'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pis')

    # ### end Alembic commands ###
