"""define_permissions_by_role

Revision ID: 9b11cb920dd7
Revises: e389a379712f
Create Date: 2025-08-31 21:18:03.583366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b11cb920dd7'
down_revision: Union[str, Sequence[str], None] = 'e389a379712f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Definindo as permissões do administrador, todas com "gerenciar" são para tudo (criar, visualizar, editar, excluir)
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 1)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 6)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 11)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 16)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 21)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 26)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 31)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 36)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (1, 41)")

    # Definindo as permissões do gerente, todas com "gerenciar" ou "visualizar" para tudo
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 1)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 6)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 11)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 16)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 26)")
    op.execute("INSERT INTO perfis_permissoes (id_perfil, id_permissao) VALUES (2, 36)")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
