"""alter_table_registros_ponto_add_column_data_hora_ponto

Revision ID: cbfc7b6752fe
Revises: 2d2e6e6619ab
Create Date: 2025-08-31 20:59:03.119888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfc7b6752fe'
down_revision: Union[str, Sequence[str], None] = '2d2e6e6619ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_pontos', sa.Column('data_hora_ponto', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_pontos', 'data_hora_ponto')
    # ### end Alembic commands ###
