"""alter_table_empresas_nullable_fields

Revision ID: fe7ef56e34c7
Revises: 3ee38fa9bedb
Create Date: 2025-08-23 21:54:14.076249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7ef56e34c7'
down_revision: Union[str, Sequence[str], None] = '3ee38fa9bedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###
